apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: overseas-chicken-java-springboot 
  janus-idp.io/tekton: overseas-chicken-java-springboot
  backstage.io/kubernetes-id: overseas-chicken-java-springboot
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: overseas-chicken-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  